name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build
      run: |
        xcodebuild build \
          -project UIKitStudy.xcodeproj \
          -scheme UIKitStudy \
          -sdk iphonesimulator \
          -destination 'generic/platform=iOS Simulator' \
          -allowProvisioningUpdates
